Added error handling for vcs_update_all

diff --git a/_bash/functions b/_bash/functions
--- a/_bash/functions
+++ b/_bash/functions
@@ -33,11 +33,19 @@ vcs_update_all () {
                 cd $i/../ > /dev/null;
 		pwd;
                 git pull > /dev/null;
+		if [ $? -ne 0 ]; then
+		    echo "git pull error";
+		    return;
+		fi
 	done;
         for i in `find $currDir -maxdepth 5 -type d -name ".svn"`; do
                 cd $i/../ > /dev/null;
 		pwd;
                 svn up > /dev/null;
+		if [ $? -ne 0 ]; then
+		    echo "svn up error";
+		    return;
+		fi
         done;
         popd;
 }
